### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by miracle2k** [flynn-archive/strowger#16]
Organizations often have internal services that need to be protected, ideally via some centralized authentication mechanism. See for example here http://www.ginzametrics.com/blog/announcing-odin-authenticator/ or http://chairnerd.seatgeek.com/oauth-support-for-nginx-with-lua/ for write ups.

A strowger-like router is required to proxy via service discovery.

Is HTTP auth or checking a cookie something you see in strowger, or rather a separate server? As much as I would like to avoid the complexity of dealing with another proxy, both in code and in infrastructure setup, I can't help but feel that there might be too many options here to fit them into strowger.

**Comment by titanous** [comment]
We should consider this after there is a working security layer in Flynn (user auth{z,n} across all layers with plugins/hooks, transport security for communication). Once we have that in place, a natural solution for this in strowger may present itself.
