### ISSUE TITLE
Update to etcd v0.2.0

### ISSUE THREAD

**Issue by titanous** [flynn-archive/strowger#2]
go-etcd changed a bunch of stuff. Might be useful to write tests first.

**Comment by benmccann** [comment]
I'm rather new at Go. How do you pick a version of a library? It seems like it just always uses the latest from GitHub?

```
import (
    "github.com/coreos/go-etcd/etcd"
)
```

**Comment by titanous** [comment]
Go will use whatever version is on your filesystem in the Go workspace. By default the toolchain checks out the latest version from GitHub if a dependency is missing. There are a variety of dependency management tools, currently the best that I've seen is [godep](https://github.com/kr/godep), but I haven't fully evaluated the options.

**Comment by titanous** [comment]
Closed by db24453bf4252daa709fc24f21b11a1ff9865ec4.
