### ISSUE TITLE
CloudFoundry Go-Router

### ISSUE THREAD

**Issue by ProTip** [flynn-archive/strowger#20]
Hello,

It looks like CloudFoundry have put quite a bit of work into their go-router and are using it in production.  Would there be any way to capitalize on their work?

**Comment by titanous** [comment]
It's possible that there are bits that could be re-used here and there, but there are differences that need to be accounted for:
- Anything that's used would need to be in a separate package as it's Apache 2.0 licensed, and we use BSD 3-clause for everything.
- The runtime configuration system is completely different. go-router uses ephemeral NATS messages and we use etcd + discoverd.
- The static configuration system uses YAML, which we don't use in Flynn.
- They use a custom logging system (steno) that we have not adopted (the Flynn logging conventions are still a work in progress).

In the future I expect there will be many more differences. That being said, I'm happy to talk through specific items if anyone wants to attempt to port features over.
