### ISSUE TITLE
Errors Not Being Logged When Port Already Bound

### ISSUE THREAD

**Issue by andrewmunsell** [flynn-archive/strowger#21]
When bootstrapping Flynn, strowger is not correctly logging when a port is already bound.

In my case, I was running a Digital Ocean Droplet that had SSH bound to port 22. Bootstrapping failed and timed out on the "deploy-app strowger" step due to this. Checking the docker logs for the strowger container revealed an exit code of "0" and no errors in the log.

My specific case was resolved by changing the port of `sshd`, though this error should be logged during bootstrapping.

**Comment by titanous** [comment]
My current guess is that Docker is actually failing to bind the ports but the error is not being exposed.

**Comment by progrium** [comment]
So this could be reported in Docker if that's confirmed?

On Tue, Apr 22, 2014 at 5:10 PM, Jonathan Rudenberg <
notifications@github.com> wrote:

> My current guess is that Docker is actually failing to bind the ports and
> failing but the error is not being exposed.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/strowger/issues/21#issuecomment-41102345
> .

## 

Jeff Lindsay
http://progrium.com

**Comment by andrewmunsell** [comment]
Does Docker not expose the error properly for your use? Because it looks like that it does at least _report_ an error if a port is already bound:

https://github.com/dotcloud/docker/issues/3224

**Comment by titanous** [comment]
I think flynn-bootstrap isn't reading the error from docker.
