### ISSUE TITLE
Proxy to a HTTPS backend

### ISSUE THREAD

**Issue by miracle2k** [flynn-archive/strowger#29]
I have a service that I want to run behind strowger - it only exposes HTTPS.

I would prefer for strowger to terminate SSL though, rather than proxying on a TCP level. 

I.e. I would need something like the "ssl" option of HAProxy: 

http://cbonte.github.io/haproxy-dconv/configuration-1.5.html#5.2-ssl

Any opposition to supporting this?

**Comment by titanous** [comment]
:+1:
